name: Deploy HTML Files to SharePoint

on:
  push:
    branches:
      - main
    paths:
      - 'html/*.html'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload HTML files to SharePoint
      env:
        SHAREPOINT_URL: ${{ secrets.SHAREPOINT_URL }}
        SHAREPOINT_USERNAME: ${{ secrets.SHAREPOINT_USERNAME }}
        SHAREPOINT_PASSWORD: ${{ secrets.SHAREPOINT_PASSWORD }}
      run: |
        for file in $(find html -name "*.html"); do
          curl --ntlm --user "$SHAREPOINT_USERNAME:$SHAREPOINT_PASSWORD" \
            --upload-file "$file" \
            "$SHAREPOINT_URL/sites/YOUR_SITE_NAME/Shared%20Documents/html/$(basename "$file")"
        done
